/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useMemo, useContext, createContext, forwardRef } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()

// This Instances component is for performance.
// Note the change to use the renamed model file.
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/energy_bar_v2.glb')
  const instances = useMemo(
    () => ({
      pCube3_aiStandardSurface1_0: nodes.pCube3_aiStandardSurface1_0,
      pCube6_aiStandardSurface2_0: nodes.pCube6_aiStandardSurface2_0,
      pCube7_aiStandardSurface2_0: nodes.pCube7_aiStandardSurface2_0,
      pCube8_aiStandardSurface2_0: nodes.pCube8_aiStandardSurface2_0,
      pCube9_aiStandardSurface2_0: nodes.pCube9_aiStandardSurface2_0,
      pCube10_aiStandardSurface2_0: nodes.pCube10_aiStandardSurface2_0,
      pCube11_aiStandardSurface2_0: nodes.pCube11_aiStandardSurface2_0,
      pCube12_aiStandardSurface2_0: nodes.pCube12_aiStandardSurface2_0,
      pCube13_aiStandardSurface2_0: nodes.pCube13_aiStandardSurface2_0,
      pCube14_aiStandardSurface2_0: nodes.pCube14_aiStandardSurface2_0,
      pCube15_aiStandardSurface2_0: nodes.pCube15_aiStandardSurface2_0,
      pCube16_aiStandardSurface2_0: nodes.pCube16_aiStandardSurface2_0,
      pCube17_aiStandardSurface2_0: nodes.pCube17_aiStandardSurface2_0,
      pCube18_aiStandardSurface2_0: nodes.pCube18_aiStandardSurface2_0,
      pCube19_aiStandardSurface2_0: nodes.pCube19_aiStandardSurface2_0,
      pCube20_aiStandardSurface2_0: nodes.pCube20_aiStandardSurface2_0,
      pCube21_aiStandardSurface2_0: nodes.pCube21_aiStandardSurface2_0,
      pCube22_aiStandardSurface2_0: nodes.pCube22_aiStandardSurface2_0,
      pCube23_aiStandardSurface2_0: nodes.pCube23_aiStandardSurface2_0,
      pCube24_aiStandardSurface2_0: nodes.pCube24_aiStandardSurface2_0,
      pCube25_aiStandardSurface2_0: nodes.pCube25_aiStandardSurface2_0,
      pCube26_aiStandardSurface2_0: nodes.pCube26_aiStandardSurface2_0,
      pCube27_aiStandardSurface2_0: nodes.pCube27_aiStandardSurface2_0,
      pCube28_aiStandardSurface2_0: nodes.pCube28_aiStandardSurface2_0,
      pCube29_aiStandardSurface2_0: nodes.pCube29_aiStandardSurface2_0,
      pCube30_aiStandardSurface2_0: nodes.pCube30_aiStandardSurface2_0,
      pCube31_aiStandardSurface2_0: nodes.pCube31_aiStandardSurface2_0,
      pCube32_aiStandardSurface2_0: nodes.pCube32_aiStandardSurface2_0,
      pCube33_aiStandardSurface2_0: nodes.pCube33_aiStandardSurface2_0,
      pCube34_aiStandardSurface2_0: nodes.pCube34_aiStandardSurface2_0,
      pCube35_aiStandardSurface2_0: nodes.pCube35_aiStandardSurface2_0,
      pCube36_aiStandardSurface2_0: nodes.pCube36_aiStandardSurface2_0,
      pCube37_aiStandardSurface2_0: nodes.pCube37_aiStandardSurface2_0,
      pCube38_aiStandardSurface2_0: nodes.pCube38_aiStandardSurface2_0,
      pCube39_aiStandardSurface2_0: nodes.pCube39_aiStandardSurface2_0,
      pCube40_aiStandardSurface2_0: nodes.pCube40_aiStandardSurface2_0,
      pCube41_aiStandardSurface2_0: nodes.pCube41_aiStandardSurface2_0,
      pCube42_aiStandardSurface2_0: nodes.pCube42_aiStandardSurface2_0,
      pCube43_aiStandardSurface2_0: nodes.pCube43_aiStandardSurface2_0,
      pCube44_aiStandardSurface2_0: nodes.pCube44_aiStandardSurface2_0,
      pCube45_aiStandardSurface2_0: nodes.pCube45_aiStandardSurface2_0,
      pCube46_aiStandardSurface2_0: nodes.pCube46_aiStandardSurface2_0,
      pCube47_aiStandardSurface2_0: nodes.pCube47_aiStandardSurface2_0,
      pCube48_aiStandardSurface2_0: nodes.pCube48_aiStandardSurface2_0,
      pCube49_aiStandardSurface2_0: nodes.pCube49_aiStandardSurface2_0,
      pCube50_aiStandardSurface2_0: nodes.pCube50_aiStandardSurface2_0,
      pCube51_aiStandardSurface2_0: nodes.pCube51_aiStandardSurface2_0,
      pCube52_aiStandardSurface2_0: nodes.pCube52_aiStandardSurface2_0,
      pCube53_aiStandardSurface2_0: nodes.pCube53_aiStandardSurface2_0,
      pCube54_aiStandardSurface2_0: nodes.pCube54_aiStandardSurface2_0,
      pCube55_aiStandardSurface2_0: nodes.pCube55_aiStandardSurface2_0,
      pCube56_aiStandardSurface2_0: nodes.pCube56_aiStandardSurface2_0,
      pCube57_aiStandardSurface2_0: nodes.pCube57_aiStandardSurface2_0,
      pCube58_aiStandardSurface2_0: nodes.pCube58_aiStandardSurface2_0,
      pCube59_aiStandardSurface2_0: nodes.pCube59_aiStandardSurface2_0,
      pCube60_aiStandardSurface2_0: nodes.pCube60_aiStandardSurface2_0,
      pCube61_aiStandardSurface2_0: nodes.pCube61_aiStandardSurface2_0,
      pCube62_aiStandardSurface2_0: nodes.pCube62_aiStandardSurface2_0,
      pCube63_aiStandardSurface2_0: nodes.pCube63_aiStandardSurface2_0,
      pCube64_aiStandardSurface2_0: nodes.pCube64_aiStandardSurface2_0,
      pCube65_aiStandardSurface2_0: nodes.pCube65_aiStandardSurface2_0,
      pCube66_aiStandardSurface2_0: nodes.pCube66_aiStandardSurface2_0,
      pCube67_aiStandardSurface2_0: nodes.pCube67_aiStandardSurface2_0,
      pCube68_aiStandardSurface2_0: nodes.pCube68_aiStandardSurface2_0,
      pCube69_aiStandardSurface2_0: nodes.pCube69_aiStandardSurface2_0,
      pCube70_aiStandardSurface2_0: nodes.pCube70_aiStandardSurface2_0,
      pCube71_aiStandardSurface2_0: nodes.pCube71_aiStandardSurface2_0,
      pCube72_aiStandardSurface2_0: nodes.pCube72_aiStandardSurface2_0,
      pCube73_aiStandardSurface2_0: nodes.pCube73_aiStandardSurface2_0,
      pCube74_aiStandardSurface2_0: nodes.pCube74_aiStandardSurface2_0,
      pCube75_aiStandardSurface2_0: nodes.pCube75_aiStandardSurface2_0,
      pCube76_aiStandardSurface2_0: nodes.pCube76_aiStandardSurface2_0,
      pCube77_aiStandardSurface2_0: nodes.pCube77_aiStandardSurface2_0,
      pCube78_aiStandardSurface2_0: nodes.pCube78_aiStandardSurface2_0,
      pCube79_aiStandardSurface2_0: nodes.pCube79_aiStandardSurface2_0,
      pCube80_aiStandardSurface2_0: nodes.pCube80_aiStandardSurface2_0,
      pCube81_aiStandardSurface2_0: nodes.pCube81_aiStandardSurface2_0,
      pCube82_aiStandardSurface2_0: nodes.pCube82_aiStandardSurface2_0,
      pCube83_aiStandardSurface2_0: nodes.pCube83_aiStandardSurface2_0,
      pCube84_aiStandardSurface2_0: nodes.pCube84_aiStandardSurface2_0,
      pCube85_aiStandardSurface2_0: nodes.pCube85_aiStandardSurface2_0,
      pCube86_aiStandardSurface2_0: nodes.pCube86_aiStandardSurface2_0,
      pCube87_aiStandardSurface2_0: nodes.pCube87_aiStandardSurface2_0,
      pCube88_aiStandardSurface2_0: nodes.pCube88_aiStandardSurface2_0,
      pCube89_aiStandardSurface2_0: nodes.pCube89_aiStandardSurface2_0,
      pCube90_aiStandardSurface2_0: nodes.pCube90_aiStandardSurface2_0,
      pCube91_aiStandardSurface2_0: nodes.pCube91_aiStandardSurface2_0,
      pCube92_aiStandardSurface2_0: nodes.pCube92_aiStandardSurface2_0,
      pCube93_aiStandardSurface2_0: nodes.pCube93_aiStandardSurface2_0,
      pCube94_aiStandardSurface2_0: nodes.pCube94_aiStandardSurface2_0,
      pCube95_aiStandardSurface2_0: nodes.pCube95_aiStandardSurface2_0,
      pCube96_aiStandardSurface2_0: nodes.pCube96_aiStandardSurface2_0,
      pCube97_aiStandardSurface2_0: nodes.pCube97_aiStandardSurface2_0,
      pCube98_aiStandardSurface2_0: nodes.pCube98_aiStandardSurface2_0,
      pCube99_aiStandardSurface2_0: nodes.pCube99_aiStandardSurface2_0,
      pCube100_aiStandardSurface2_0: nodes.pCube100_aiStandardSurface2_0,
      pCube101_aiStandardSurface2_0: nodes.pCube101_aiStandardSurface2_0,
      pCube102_aiStandardSurface2_0: nodes.pCube102_aiStandardSurface2_0,
      pCube103_aiStandardSurface2_0: nodes.pCube103_aiStandardSurface2_0,
      pCube104_aiStandardSurface2_0: nodes.pCube104_aiStandardSurface2_0,
      pCube105_aiStandardSurface2_0: nodes.pCube105_aiStandardSurface2_0,
      pCube106_aiStandardSurface2_0: nodes.pCube106_aiStandardSurface2_0,
      pCube107_aiStandardSurface2_0: nodes.pCube107_aiStandardSurface2_0,
      pCube108_aiStandardSurface2_0: nodes.pCube108_aiStandardSurface2_0,
      pCube109_aiStandardSurface2_0: nodes.pCube109_aiStandardSurface2_0,
      pCube110_aiStandardSurface2_0: nodes.pCube110_aiStandardSurface2_0,
      pCube111_aiStandardSurface2_0: nodes.pCube111_aiStandardSurface2_0,
      pCube112_aiStandardSurface2_0: nodes.pCube112_aiStandardSurface2_0,
      pCube113_aiStandardSurface2_0: nodes.pCube113_aiStandardSurface2_0,
      pCube114_aiStandardSurface2_0: nodes.pCube114_aiStandardSurface2_0,
      pCube115_aiStandardSurface2_0: nodes.pCube115_aiStandardSurface2_0,
      pCube116_aiStandardSurface2_0: nodes.pCube116_aiStandardSurface2_0,
      pCube117_aiStandardSurface2_0: nodes.pCube117_aiStandardSurface2_0,
      pCube118_aiStandardSurface2_0: nodes.pCube118_aiStandardSurface2_0,
      pCube119_aiStandardSurface2_0: nodes.pCube119_aiStandardSurface2_0,
      pCube120_aiStandardSurface2_0: nodes.pCube120_aiStandardSurface2_0,
      pCube121_aiStandardSurface2_0: nodes.pCube121_aiStandardSurface2_0,
      pCube122_aiStandardSurface2_0: nodes.pCube122_aiStandardSurface2_0,
      pCube123_aiStandardSurface2_0: nodes.pCube123_aiStandardSurface2_0,
      pCube124_aiStandardSurface2_0: nodes.pCube124_aiStandardSurface2_0,
      pCube125_aiStandardSurface2_0: nodes.pCube125_aiStandardSurface2_0,
      pCube126_aiStandardSurface2_0: nodes.pCube126_aiStandardSurface2_0,
      pCube127_aiStandardSurface2_0: nodes.pCube127_aiStandardSurface2_0,
      pCube128_aiStandardSurface2_0: nodes.pCube128_aiStandardSurface2_0,
      pCube129_aiStandardSurface2_0: nodes.pCube129_aiStandardSurface2_0,
      pCube130_aiStandardSurface2_0: nodes.pCube130_aiStandardSurface2_0,
      pCube131_aiStandardSurface2_0: nodes.pCube131_aiStandardSurface2_0,
      pCube132_aiStandardSurface2_0: nodes.pCube132_aiStandardSurface2_0,
      pCube133_aiStandardSurface2_0: nodes.pCube133_aiStandardSurface2_0,
      pCube134_aiStandardSurface2_0: nodes.pCube134_aiStandardSurface2_0,
      pCube135_aiStandardSurface2_0: nodes.pCube135_aiStandardSurface2_0,
      pCube136_aiStandardSurface2_0: nodes.pCube136_aiStandardSurface2_0,
      pCube137_aiStandardSurface2_0: nodes.pCube137_aiStandardSurface2_0,
      pCube138_aiStandardSurface2_0: nodes.pCube138_aiStandardSurface2_0,
      pCube139_aiStandardSurface2_0: nodes.pCube139_aiStandardSurface2_0,
      pCube140_aiStandardSurface2_0: nodes.pCube140_aiStandardSurface2_0,
      pCube141_aiStandardSurface2_0: nodes.pCube141_aiStandardSurface2_0,
      pCube142_aiStandardSurface2_0: nodes.pCube142_aiStandardSurface2_0,
      pCube143_aiStandardSurface2_0: nodes.pCube143_aiStandardSurface2_0,
      pCube144_aiStandardSurface2_0: nodes.pCube144_aiStandardSurface2_0,
      pCube145_aiStandardSurface2_0: nodes.pCube145_aiStandardSurface2_0,
      pCube146_aiStandardSurface2_0: nodes.pCube146_aiStandardSurface2_0,
      pCube147_aiStandardSurface2_0: nodes.pCube147_aiStandardSurface2_0,
      pCube148_aiStandardSurface2_0: nodes.pCube148_aiStandardSurface2_0,
      pCube149_aiStandardSurface2_0: nodes.pCube149_aiStandardSurface2_0,
      pCube150_aiStandardSurface2_0: nodes.pCube150_aiStandardSurface2_0,
      pCube151_aiStandardSurface2_0: nodes.pCube151_aiStandardSurface2_0,
      pCube152_aiStandardSurface2_0: nodes.pCube152_aiStandardSurface2_0,
      pCube153_aiStandardSurface2_0: nodes.pCube153_aiStandardSurface2_0,
      pCube154_aiStandardSurface2_0: nodes.pCube154_aiStandardSurface2_0,
      pCube155_aiStandardSurface2_0: nodes.pCube155_aiStandardSurface2_0,
      pCube156_aiStandardSurface2_0: nodes.pCube156_aiStandardSurface2_0,
      pCube157_aiStandardSurface2_0: nodes.pCube157_aiStandardSurface2_0,
      pCube158_aiStandardSurface2_0: nodes.pCube158_aiStandardSurface2_0,
      pCube159_aiStandardSurface2_0: nodes.pCube159_aiStandardSurface2_0,
      pCube160_aiStandardSurface2_0: nodes.pCube160_aiStandardSurface2_0,
      pCube161_aiStandardSurface2_0: nodes.pCube161_aiStandardSurface2_0,
      pCube162_aiStandardSurface2_0: nodes.pCube162_aiStandardSurface2_0,
      pCube163_aiStandardSurface2_0: nodes.pCube163_aiStandardSurface2_0,
      pCube164_aiStandardSurface2_0: nodes.pCube164_aiStandardSurface2_0,
      pCube165_aiStandardSurface2_0: nodes.pCube165_aiStandardSurface2_0,
      pCube166_aiStandardSurface2_0: nodes.pCube166_aiStandardSurface2_0,
      pCube167_aiStandardSurface2_0: nodes.pCube167_aiStandardSurface2_0,
      pCube168_aiStandardSurface2_0: nodes.pCube168_aiStandardSurface2_0,
      pCube169_aiStandardSurface2_0: nodes.pCube169_aiStandardSurface2_0,
      pCube170_aiStandardSurface3_0: nodes.pCube170_aiStandardSurface3_0,
      pCube171_aiStandardSurface3_0: nodes.pCube171_aiStandardSurface3_0,
      pCube172_aiStandardSurface3_0: nodes.pCube172_aiStandardSurface3_0,
      pCube173_aiStandardSurface3_0: nodes.pCube173_aiStandardSurface3_0,
      pCube174_aiStandardSurface3_0: nodes.pCube174_aiStandardSurface3_0,
      pCube175_aiStandardSurface3_0: nodes.pCube175_aiStandardSurface3_0,
      pCube176_aiStandardSurface3_0: nodes.pCube176_aiStandardSurface3_0,
      pCube177_aiStandardSurface3_0: nodes.pCube177_aiStandardSurface3_0,
      pCube178_aiStandardSurface3_0: nodes.pCube178_aiStandardSurface3_0,
      pCube179_aiStandardSurface3_0: nodes.pCube179_aiStandardSurface3_0,
      pCube180_aiStandardSurface3_0: nodes.pCube180_aiStandardSurface3_0,
      pCube181_aiStandardSurface3_0: nodes.pCube181_aiStandardSurface3_0,
      pCube182_aiStandardSurface3_0: nodes.pCube182_aiStandardSurface3_0,
      pCube183_aiStandardSurface3_0: nodes.pCube183_aiStandardSurface3_0,
      pCube184_aiStandardSurface3_0: nodes.pCube184_aiStandardSurface3_0,
      pCube185_aiStandardSurface3_0: nodes.pCube185_aiStandardSurface3_0,
      pCube186_aiStandardSurface3_0: nodes.pCube186_aiStandardSurface3_0,
      pCube187_aiStandardSurface3_0: nodes.pCube187_aiStandardSurface3_0,
      pCube188_aiStandardSurface3_0: nodes.pCube188_aiStandardSurface3_0,
      pCube189_aiStandardSurface3_0: nodes.pCube189_aiStandardSurface3_0,
      pCube190_aiStandardSurface3_0: nodes.pCube190_aiStandardSurface3_0,
      pCube191_aiStandardSurface3_0: nodes.pCube191_aiStandardSurface3_0,
      pCube192_aiStandardSurface3_0: nodes.pCube192_aiStandardSurface3_0,
      pCube193_aiStandardSurface3_0: nodes.pCube193_aiStandardSurface3_0,
      pCube194_aiStandardSurface3_0: nodes.pCube194_aiStandardSurface3_0,
      pCube195_aiStandardSurface3_0: nodes.pCube195_aiStandardSurface3_0,
      pCube196_aiStandardSurface3_0: nodes.pCube196_aiStandardSurface3_0,
      pCube197_aiStandardSurface3_0: nodes.pCube197_aiStandardSurface3_0,
      pCube198_aiStandardSurface3_0: nodes.pCube198_aiStandardSurface3_0,
      pCube199_aiStandardSurface3_0: nodes.pCube199_aiStandardSurface3_0,
      pCube200_aiStandardSurface3_0: nodes.pCube200_aiStandardSurface3_0,
      pCube201_aiStandardSurface3_0: nodes.pCube201_aiStandardSurface3_0,
      pCube202_aiStandardSurface3_0: nodes.pCube202_aiStandardSurface3_0,
      pCube203_aiStandardSurface3_0: nodes.pCube203_aiStandardSurface3_0,
      pCube204_aiStandardSurface3_0: nodes.pCube204_aiStandardSurface3_0,
      pCube205_aiStandardSurface3_0: nodes.pCube205_aiStandardSurface3_0,
      pCube206_aiStandardSurface3_0: nodes.pCube206_aiStandardSurface3_0,
      pCube207_aiStandardSurface3_0: nodes.pCube207_aiStandardSurface3_0,
      pCube208_aiStandardSurface3_0: nodes.pCube208_aiStandardSurface3_0,
      pCube209_aiStandardSurface3_0: nodes.pCube209_aiStandardSurface3_0,
      pCube210_aiStandardSurface3_0: nodes.pCube210_aiStandardSurface3_0,
      pCube211_aiStandardSurface3_0: nodes.pCube211_aiStandardSurface3_0,
      pCube212_aiStandardSurface3_0: nodes.pCube212_aiStandardSurface3_0,
      pCube213_aiStandardSurface3_0: nodes.pCube213_aiStandardSurface3_0,
      pCube214_aiStandardSurface3_0: nodes.pCube214_aiStandardSurface3_0,
      pCube215_aiStandardSurface3_0: nodes.pCube215_aiStandardSurface3_0,
      pCube216_aiStandardSurface3_0: nodes.pCube216_aiStandardSurface3_0,
      pCube217_aiStandardSurface3_0: nodes.pCube217_aiStandardSurface3_0,
      pCube218_aiStandardSurface3_0: nodes.pCube218_aiStandardSurface3_0,
      pCube219_aiStandardSurface3_0: nodes.pCube219_aiStandardSurface3_0,
      pCube220_aiStandardSurface3_0: nodes.pCube220_aiStandardSurface3_0,
      pCube221_aiStandardSurface3_0: nodes.pCube221_aiStandardSurface3_0,
      pCube222_aiStandardSurface3_0: nodes.pCube222_aiStandardSurface3_0,
      pCube223_aiStandardSurface3_0: nodes.pCube223_aiStandardSurface3_0,
      pCube224_aiStandardSurface3_0: nodes.pCube224_aiStandardSurface3_0,
      pCube225_aiStandardSurface3_0: nodes.pCube225_aiStandardSurface3_0,
      pCube226_aiStandardSurface3_0: nodes.pCube226_aiStandardSurface3_0,
      pCube227_aiStandardSurface3_0: nodes.pCube227_aiStandardSurface3_0,
      pCube228_aiStandardSurface3_0: nodes.pCube228_aiStandardSurface3_0,
      pCube229_aiStandardSurface3_0: nodes.pCube229_aiStandardSurface3_0,
      pCube230_aiStandardSurface3_0: nodes.pCube230_aiStandardSurface3_0,
      pCube231_aiStandardSurface3_0: nodes.pCube231_aiStandardSurface3_0,
      pCube232_aiStandardSurface3_0: nodes.pCube232_aiStandardSurface3_0,
      pCube233_aiStandardSurface3_0: nodes.pCube233_aiStandardSurface3_0,
      pCube234_aiStandardSurface3_0: nodes.pCube234_aiStandardSurface3_0,
      pCube235_aiStandardSurface3_0: nodes.pCube235_aiStandardSurface3_0,
      pCube236_aiStandardSurface3_0: nodes.pCube236_aiStandardSurface3_0,
      pCube237_aiStandardSurface3_0: nodes.pCube237_aiStandardSurface3_0,
      pCube238_aiStandardSurface3_0: nodes.pCube238_aiStandardSurface3_0,
      pCube239_aiStandardSurface3_0: nodes.pCube239_aiStandardSurface3_0,
      pCube240_aiStandardSurface3_0: nodes.pCube240_aiStandardSurface3_0,
      pCube241_aiStandardSurface3_0: nodes.pCube241_aiStandardSurface3_0,
      pCube242_aiStandardSurface3_0: nodes.pCube242_aiStandardSurface3_0,
      pCube243_aiStandardSurface3_0: nodes.pCube243_aiStandardSurface3_0,
      pCube244_aiStandardSurface3_0: nodes.pCube244_aiStandardSurface3_0,
      pCube245_aiStandardSurface3_0: nodes.pCube245_aiStandardSurface3_0,
      pCube246_aiStandardSurface3_0: nodes.pCube246_aiStandardSurface3_0,
      pCube247_aiStandardSurface3_0: nodes.pCube247_aiStandardSurface3_0,
      pCube248_aiStandardSurface3_0: nodes.pCube248_aiStandardSurface3_0,
      pCube249_aiStandardSurface3_0: nodes.pCube249_aiStandardSurface3_0,
      pCube250_aiStandardSurface3_0: nodes.pCube250_aiStandardSurface3_0,
      pCube251_aiStandardSurface3_0: nodes.pCube251_aiStandardSurface3_0,
      pCube252_aiStandardSurface3_0: nodes.pCube252_aiStandardSurface3_0,
      pCube253_aiStandardSurface3_0: nodes.pCube253_aiStandardSurface3_0,
      pCube254_aiStandardSurface3_0: nodes.pCube254_aiStandardSurface3_0,
      pCube255_aiStandardSurface3_0: nodes.pCube255_aiStandardSurface3_0,
      pCube256_aiStandardSurface3_0: nodes.pCube256_aiStandardSurface3_0,
      pCube257_aiStandardSurface3_0: nodes.pCube257_aiStandardSurface3_0,
      pCube258_aiStandardSurface3_0: nodes.pCube258_aiStandardSurface3_0,
      pCube259_aiStandardSurface3_0: nodes.pCube259_aiStandardSurface3_0,
      pCube260_aiStandardSurface3_0: nodes.pCube260_aiStandardSurface3_0,
      pCube261_aiStandardSurface3_0: nodes.pCube261_aiStandardSurface3_0,
      pCube262_aiStandardSurface3_0: nodes.pCube262_aiStandardSurface3_0,
      pCube263_aiStandardSurface3_0: nodes.pCube263_aiStandardSurface3_0,
      pCube264_aiStandardSurface3_0: nodes.pCube264_aiStandardSurface3_0,
      pCube265_aiStandardSurface3_0: nodes.pCube265_aiStandardSurface3_0,
      pCube266_aiStandardSurface3_0: nodes.pCube266_aiStandardSurface3_0,
      pCube267_aiStandardSurface3_0: nodes.pCube267_aiStandardSurface3_0,
      pCube268_aiStandardSurface3_0: nodes.pCube268_aiStandardSurface3_0,
      pCube269_aiStandardSurface3_0: nodes.pCube269_aiStandardSurface3_0,
      pCube270_aiStandardSurface3_0: nodes.pCube270_aiStandardSurface3_0,
      pCube271_aiStandardSurface3_0: nodes.pCube271_aiStandardSurface3_0,
      pCube272_aiStandardSurface3_0: nodes.pCube272_aiStandardSurface3_0,
      pCube273_aiStandardSurface3_0: nodes.pCube273_aiStandardSurface3_0,
      pCube274_aiStandardSurface3_0: nodes.pCube274_aiStandardSurface3_0,
      pCube275_aiStandardSurface3_0: nodes.pCube275_aiStandardSurface3_0,
      pCube276_aiStandardSurface3_0: nodes.pCube276_aiStandardSurface3_0,
      pCube277_aiStandardSurface3_0: nodes.pCube277_aiStandardSurface3_0,
      pCube278_aiStandardSurface3_0: nodes.pCube278_aiStandardSurface3_0,
      pCube279_aiStandardSurface3_0: nodes.pCube279_aiStandardSurface3_0,
      pCube280_aiStandardSurface3_0: nodes.pCube280_aiStandardSurface3_0,
      pCube281_aiStandardSurface3_0: nodes.pCube281_aiStandardSurface3_0,
      pCube282_aiStandardSurface3_0: nodes.pCube282_aiStandardSurface3_0,
      pCube283_aiStandardSurface3_0: nodes.pCube283_aiStandardSurface3_0,
      pCube284_aiStandardSurface3_0: nodes.pCube284_aiStandardSurface3_0,
      pCube285_aiStandardSurface3_0: nodes.pCube285_aiStandardSurface3_0,
      pCube286_aiStandardSurface3_0: nodes.pCube286_aiStandardSurface3_0,
      pCube287_aiStandardSurface3_0: nodes.pCube287_aiStandardSurface3_0,
      pCube288_aiStandardSurface3_0: nodes.pCube288_aiStandardSurface3_0,
      pCube289_aiStandardSurface3_0: nodes.pCube289_aiStandardSurface3_0,
      pCube290_aiStandardSurface3_0: nodes.pCube290_aiStandardSurface3_0,
      pCube291_aiStandardSurface3_0: nodes.pCube291_aiStandardSurface3_0,
      pCube292_aiStandardSurface3_0: nodes.pCube292_aiStandardSurface3_0,
      pCube293_aiStandardSurface3_0: nodes.pCube293_aiStandardSurface3_0,
      pCube294_aiStandardSurface3_0: nodes.pCube294_aiStandardSurface3_0,
      pCube295_aiStandardSurface3_0: nodes.pCube295_aiStandardSurface3_0,
      pCube296_aiStandardSurface3_0: nodes.pCube296_aiStandardSurface3_0,
      pCube297_aiStandardSurface3_0: nodes.pCube297_aiStandardSurface3_0,
      pCube298_aiStandardSurface3_0: nodes.pCube298_aiStandardSurface3_0,
      pCube299_aiStandardSurface3_0: nodes.pCube299_aiStandardSurface3_0,
      pCube300_aiStandardSurface3_0: nodes.pCube300_aiStandardSurface3_0,
      pCube301_aiStandardSurface3_0: nodes.pCube301_aiStandardSurface3_0,
      pCube302_aiStandardSurface3_0: nodes.pCube302_aiStandardSurface3_0,
      pCube303_aiStandardSurface3_0: nodes.pCube303_aiStandardSurface3_0,
      pCube304_aiStandardSurface3_0: nodes.pCube304_aiStandardSurface3_0,
      pCube305_aiStandardSurface3_0: nodes.pCube305_aiStandardSurface3_0,
      pCube306_aiStandardSurface3_0: nodes.pCube306_aiStandardSurface3_0,
      pCube307_aiStandardSurface3_0: nodes.pCube307_aiStandardSurface3_0,
      pCube308_aiStandardSurface3_0: nodes.pCube308_aiStandardSurface3_0,
      pCube309_aiStandardSurface3_0: nodes.pCube309_aiStandardSurface3_0,
      pCube310_aiStandardSurface3_0: nodes.pCube310_aiStandardSurface3_0,
      pCube311_aiStandardSurface3_0: nodes.pCube311_aiStandardSurface3_0,
      pCube312_aiStandardSurface3_0: nodes.pCube312_aiStandardSurface3_0,
      pCube313_aiStandardSurface3_0: nodes.pCube313_aiStandardSurface3_0,
      pCube314_aiStandardSurface3_0: nodes.pCube314_aiStandardSurface3_0,
      pCube315_aiStandardSurface3_0: nodes.pCube315_aiStandardSurface3_0,
      pCube316_aiStandardSurface3_0: nodes.pCube316_aiStandardSurface3_0,
      pCube317_aiStandardSurface3_0: nodes.pCube317_aiStandardSurface3_0,
      pCube318_aiStandardSurface3_0: nodes.pCube318_aiStandardSurface3_0,
      pCube319_aiStandardSurface3_0: nodes.pCube319_aiStandardSurface3_0,
      pCube320_aiStandardSurface3_0: nodes.pCube320_aiStandardSurface3_0,
      pCube321_aiStandardSurface3_0: nodes.pCube321_aiStandardSurface3_0,
      pCube322_aiStandardSurface3_0: nodes.pCube322_aiStandardSurface3_0,
      pCube323_aiStandardSurface3_0: nodes.pCube323_aiStandardSurface3_0,
      pCube324_aiStandardSurface3_0: nodes.pCube324_aiStandardSurface3_0,
      pCube325_aiStandardSurface3_0: nodes.pCube325_aiStandardSurface3_0,
      pCube326_aiStandardSurface3_0: nodes.pCube326_aiStandardSurface3_0,
      pCube327_aiStandardSurface3_0: nodes.pCube327_aiStandardSurface3_0,
      pCube328_aiStandardSurface3_0: nodes.pCube328_aiStandardSurface3_0,
      pCube329_aiStandardSurface3_0: nodes.pCube329_aiStandardSurface3_0
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="2e7513e960664aedaff860fe2491e0b6fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="group5">
                <group name="group4" rotation={[-0.048, 0.025, 0.139]}>
                  <group name="pCube3" scale={[20.612, 5.842, 3.519]}>
                    <instances.pCube3_aiStandardSurface1_0 />
                  </group>
                  <group name="group2">
                    <group name="pCube6" position={[-11.263, 4.109, -0.001]} rotation={[-1.574, 0.075, -0.003]} scale={[0.536, 0.022, 0.034]}><instances.pCube6_aiStandardSurface2_0/></group>
                    <group name="pCube7" position={[-11.267, 4.025, -0.015]} rotation={[2.942, -0.078, 0.013]} scale={[0.536, 0.047, 0.034]}><instances.pCube7_aiStandardSurface2_0/></group>
                    <group name="pCube8" position={[-11.256, 3.947, -0.003]} rotation={[2.943, -0.102, 0.013]} scale={[0.536, 0.047, 0.034]}><instances.pCube8_aiStandardSurface2_0/></group>
                    <group name="pCube9" position={[-11.262, 3.855, 0.013]} rotation={[3.033, -0.1, 0.022]} scale={[0.536, 0.047, 0.034]}><instances.pCube9_aiStandardSurface2_0/></group>
                    <group name="pCube10" position={[-11.265, 3.758, 0.02]} rotation={[3.033, -0.1, 0.022]} scale={[0.536, 0.047, 0.034]}><instances.pCube10_aiStandardSurface2_0/></group>
                    <group name="pCube11" position={[-11.283, 3.669, 0.026]} rotation={[3.033, -0.1, 0.022]} scale={[0.536, 0.047, 0.034]}><instances.pCube11_aiStandardSurface2_0/></group>
                    <group name="pCube12" position={[-11.287, 3.572, 0.032]} rotation={[3.033, -0.1, 0.022]} scale={[0.536, 0.047, 0.034]}><instances.pCube12_aiStandardSurface2_0/></group>
                    <group name="pCube13" position={[-11.294, 3.476, 0.038]} rotation={[3.087, -0.095, 0.027]} scale={[0.536, 0.047, 0.034]}><instances.pCube13_aiStandardSurface2_0/></group>
                    <group name="pCube14" position={[-11.313, 3.377, 0.047]} rotation={[3.087, -0.095, 0.027]} scale={[0.536, 0.047, 0.034]}><instances.pCube14_aiStandardSurface2_0/></group>
                    <group name="pCube15" position={[-11.321, 3.283, 0.05]} rotation={[-3.125, -0.093, 0.034]} scale={[0.536, 0.047, 0.034]}><instances.pCube15_aiStandardSurface2_0/></group>
                    <group name="pCube16" position={[-11.328, 3.185, 0.047]} rotation={[-3.125, -0.093, 0.034]} scale={[0.536, 0.047, 0.034]}><instances.pCube16_aiStandardSurface2_0/></group>
                    <group name="pCube17" position={[-11.339, 3.082, 0.043]} rotation={[-3.125, -0.093, 0.034]} scale={[0.536, 0.047, 0.034]}><instances.pCube17_aiStandardSurface2_0/></group>
                    <group name="pCube18" position={[-11.345, 2.982, 0.041]} rotation={[-3.125, -0.093, 0.034]} scale={[0.536, 0.047, 0.034]}><instances.pCube18_aiStandardSurface2_0/></group>
                    <group name="pCube19" position={[-11.362, 2.879, 0.038]} rotation={[-3.125, -0.093, 0.034]} scale={[0.536, 0.047, 0.034]}><instances.pCube19_aiStandardSurface2_0/></group>
                    <group name="pCube20" position={[-11.357, 2.778, 0.035]} rotation={[-3.125, -0.093, 0.034]} scale={[0.536, 0.047, 0.034]}><instances.pCube20_aiStandardSurface2_0/></group>
                    <group name="pCube21" position={[-11.36, 2.682, 0.031]} rotation={[-3.125, -0.093, 0.034]} scale={[0.536, 0.047, 0.034]}><instances.pCube21_aiStandardSurface2_0/></group>
                    <group name="pCube22" position={[-11.361, 2.584, 0.027]} rotation={[-3.078, -0.081, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube22_aiStandardSurface2_0/></group>
                    <group name="pCube23" position={[-11.348, 2.482, 0.019]} rotation={[-3.078, -0.081, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube23_aiStandardSurface2_0/></group>
                    <group name="pCube24" position={[-11.347, 2.384, 0.015]} rotation={[-3.078, -0.081, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube24_aiStandardSurface2_0/></group>
                    <group name="pCube25" position={[-11.336, 2.284, 0.007]} rotation={[-3.078, -0.081, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube25_aiStandardSurface2_0/></group>
                    <group name="pCube26" position={[-11.328, 2.184, 0.001]} rotation={[-3.078, -0.081, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube26_aiStandardSurface2_0/></group>
                    <group name="pCube27" position={[-11.331, 2.088, -0.004]} rotation={[-3.078, -0.087, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube27_aiStandardSurface2_0/></group>
                    <group name="pCube28" position={[-11.324, 1.987, -0.011]} rotation={[-3.078, -0.087, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube28_aiStandardSurface2_0/></group>
                    <group name="pCube29" position={[-11.315, 1.885, -0.017]} rotation={[-3.078, -0.087, 0.039]} scale={[0.536, 0.047, 0.034]}><instances.pCube29_aiStandardSurface2_0/></group>
                    <group name="pCube30" position={[-11.31, 1.777, -0.023]} rotation={[-3.078, -0.087, -0.001]} scale={[0.536, 0.047, 0.034]}><instances.pCube30_aiStandardSurface2_0/></group>
                    <group name="pCube31" position={[-11.3, 1.677, -0.028]} rotation={[-3.078, -0.087, -0.001]} scale={[0.536, 0.047, 0.034]}><instances.pCube31_aiStandardSurface2_0/></group>
                    <group name="pCube32" position={[-11.289, 1.576, -0.034]} rotation={[-3.078, -0.087, -0.001]} scale={[0.536, 0.047, 0.034]}><instances.pCube32_aiStandardSurface2_0/></group>
                    <group name="pCube33" position={[-11.282, 1.473, -0.038]} rotation={[-3.078, -0.087, -0.001]} scale={[0.536, 0.047, 0.034]}><instances.pCube33_aiStandardSurface2_0/></group>
                    <group name="pCube34" position={[-11.27, 1.368, -0.042]} rotation={[-3.078, -0.087, -0.001]} scale={[0.536, 0.047, 0.034]}><instances.pCube34_aiStandardSurface2_0/></group>
                    <group name="pCube35" position={[-11.263, 1.269, -0.049]} rotation={[-3.078, -0.087, -0.001]} scale={[0.536, 0.047, 0.034]}><instances.pCube35_aiStandardSurface2_0/></group>
                    <group name="pCube36" position={[-11.242, 1.163, -0.057]} rotation={[-3.078, -0.087, -0.042]} scale={[0.536, 0.047, 0.034]}><instances.pCube36_aiStandardSurface2_0/></group>
                    <group name="pCube37" position={[-11.223, 1.061, -0.059]} rotation={[-3.078, -0.087, -0.042]} scale={[0.536, 0.047, 0.034]}><instances.pCube37_aiStandardSurface2_0/></group>
                    <group name="pCube38" position={[-11.198, 0.962, -0.064]} rotation={[-3.078, -0.087, -0.073]} scale={[0.536, 0.047, 0.034]}><instances.pCube38_aiStandardSurface2_0/></group>
                    <group name="pCube39" position={[-11.172, 0.866, -0.071]} rotation={[-3.078, -0.087, -0.055]} scale={[0.536, 0.047, 0.034]}><instances.pCube39_aiStandardSurface2_0/></group>
                    <group name="pCube40" position={[-11.153, 0.765, -0.08]} rotation={[-3.078, -0.087, -0.055]} scale={[0.536, 0.047, 0.034]}><instances.pCube40_aiStandardSurface2_0/></group>
                    <group name="pCube41" position={[-11.135, 0.666, -0.086]} rotation={[-3.078, -0.087, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube41_aiStandardSurface2_0/></group>
                    <group name="pCube42" position={[-11.102, 0.568, -0.093]} rotation={[-3.078, -0.087, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube42_aiStandardSurface2_0/></group>
                    <group name="pCube43" position={[-11.076, 0.474, -0.094]} rotation={[-3.078, -0.087, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube43_aiStandardSurface2_0/></group>
                    <group name="pCube44" position={[-11.048, 0.376, -0.101]} rotation={[-3.078, -0.087, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube44_aiStandardSurface2_0/></group>
                    <group name="pCube45" position={[-11.025, 0.278, -0.105]} rotation={[-3.078, -0.089, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube45_aiStandardSurface2_0/></group>
                    <group name="pCube46" position={[-11, 0.183, -0.107]} rotation={[-3.078, -0.089, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube46_aiStandardSurface2_0/></group>
                    <group name="pCube47" position={[-10.984, 0.086, -0.11]} rotation={[-3.078, -0.089, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube47_aiStandardSurface2_0/></group>
                    <group name="pCube48" position={[-10.965, -0.013, -0.113]} rotation={[-3.078, -0.089, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube48_aiStandardSurface2_0/></group>
                    <group name="pCube49" position={[-10.95, -0.112, -0.116]} rotation={[-3.078, -0.089, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube49_aiStandardSurface2_0/></group>
                    <group name="pCube50" position={[-10.935, -0.209, -0.119]} rotation={[-3.078, -0.089, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube50_aiStandardSurface2_0/></group>
                    <group name="pCube51" position={[-10.918, -0.31, -0.12]} rotation={[-3.078, -0.089, -0.055]} scale={[0.512, 0.047, 0.034]}><instances.pCube51_aiStandardSurface2_0/></group>
                    <group name="pCube52" position={[-10.919, -0.413, -0.12]} rotation={[3.124, -0.084, -0.062]} scale={[0.512, 0.047, 0.034]}><instances.pCube52_aiStandardSurface2_0/></group>
                    <group name="pCube53" position={[-10.914, -0.512, -0.121]} rotation={[3.124, -0.084, -0.062]} scale={[0.512, 0.047, 0.034]}><instances.pCube53_aiStandardSurface2_0/></group>
                    <group name="pCube54" position={[-10.909, -0.612, -0.118]} rotation={[3.124, -0.084, -0.062]} scale={[0.512, 0.047, 0.034]}><instances.pCube54_aiStandardSurface2_0/></group>
                    <group name="pCube55" position={[-10.907, -0.71, -0.12]} rotation={[3.124, -0.084, -0.062]} scale={[0.512, 0.047, 0.034]}><instances.pCube55_aiStandardSurface2_0/></group>
                    <group name="pCube56" position={[-10.907, -0.805, -0.12]} rotation={[3.124, -0.084, -0.032]} scale={[0.523, 0.047, 0.034]}><instances.pCube56_aiStandardSurface2_0/></group>
                    <group name="pCube57" position={[-10.917, -0.899, -0.115]} rotation={[3.124, -0.084, -0.011]} scale={[0.523, 0.047, 0.034]}><instances.pCube57_aiStandardSurface2_0/></group>
                    <group name="pCube58" position={[-10.926, -1, -0.113]} rotation={[3.124, -0.084, -0.011]} scale={[0.523, 0.047, 0.034]}><instances.pCube58_aiStandardSurface2_0/></group>
                    <group name="pCube59" position={[-10.936, -1.1, -0.107]} rotation={[3.124, -0.084, -0.011]} scale={[0.523, 0.047, 0.034]}><instances.pCube59_aiStandardSurface2_0/></group>
                    <group name="pCube60" position={[-10.947, -1.2, -0.105]} rotation={[3.124, -0.084, -0.001]} scale={[0.523, 0.047, 0.034]}><instances.pCube60_aiStandardSurface2_0/></group>
                    <group name="pCube61" position={[-10.957, -1.299, -0.102]} rotation={[3.124, -0.084, 0.017]} scale={[0.523, 0.047, 0.034]}><instances.pCube61_aiStandardSurface2_0/></group>
                    <group name="pCube62" position={[-10.96, -1.4, -0.099]} rotation={[3.124, -0.084, 0.029]} scale={[0.523, 0.047, 0.034]}><instances.pCube62_aiStandardSurface2_0/></group>
                    <group name="pCube63" position={[-10.976, -1.504, -0.094]} rotation={[3.124, -0.084, 0.041]} scale={[0.523, 0.047, 0.034]}><instances.pCube63_aiStandardSurface2_0/></group>
                    <group name="pCube64" position={[-10.981, -1.601, -0.089]} rotation={[3.124, -0.084, 0.052]} scale={[0.523, 0.047, 0.034]}><instances.pCube64_aiStandardSurface2_0/></group>
                    <group name="pCube65" position={[-10.995, -1.701, -0.084]} rotation={[3.124, -0.084, 0.052]} scale={[0.523, 0.047, 0.034]}><instances.pCube65_aiStandardSurface2_0/></group>
                    <group name="pCube66" position={[-11.005, -1.799, -0.08]} rotation={[3.124, -0.084, 0.052]} scale={[0.523, 0.047, 0.034]}><instances.pCube66_aiStandardSurface2_0/></group>
                    <group name="pCube67" position={[-11.012, -1.897, -0.076]} rotation={[3.124, -0.084, 0.052]} scale={[0.523, 0.047, 0.034]}><instances.pCube67_aiStandardSurface2_0/></group>
                    <group name="pCube68" position={[-11.018, -1.991, -0.072]} rotation={[3.124, -0.084, 0.052]} scale={[0.523, 0.047, 0.034]}><instances.pCube68_aiStandardSurface2_0/></group>
                    <group name="pCube69" position={[-11.019, -2.096, -0.068]} rotation={[3.124, -0.084, 0.024]} scale={[0.523, 0.047, 0.034]}><instances.pCube69_aiStandardSurface2_0/></group>
                    <group name="pCube70" position={[-11.013, -2.204, -0.067]} rotation={[3.124, -0.084, 0.003]} scale={[0.523, 0.047, 0.034]}><instances.pCube70_aiStandardSurface2_0/></group>
                    <group name="pCube71" position={[-11.012, -2.303, -0.063]} rotation={[3.124, -0.084, 0.003]} scale={[0.523, 0.047, 0.034]}><instances.pCube71_aiStandardSurface2_0/></group>
                    <group name="pCube72" position={[-11.012, -2.406, -0.059]} rotation={[3.124, -0.084, 0.003]} scale={[0.523, 0.047, 0.034]}><instances.pCube72_aiStandardSurface2_0/></group>
                    <group name="pCube73" position={[-11.01, -2.51, -0.056]} rotation={[3.124, -0.084, -0.009]} scale={[0.523, 0.047, 0.034]}><instances.pCube73_aiStandardSurface2_0/></group>
                    <group name="pCube74" position={[-11.009, -2.62, -0.052]} rotation={[3.102, -0.078, -0.037]} scale={[0.523, 0.047, 0.034]}><instances.pCube74_aiStandardSurface2_0/></group>
                    <group name="pCube75" position={[-11, -2.722, -0.051]} rotation={[3.102, -0.078, -0.053]} scale={[0.523, 0.047, 0.034]}><instances.pCube75_aiStandardSurface2_0/></group>
                    <group name="pCube76" position={[-10.994, -2.833, -0.047]} rotation={[3.102, -0.078, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube76_aiStandardSurface2_0/></group>
                    <group name="pCube77" position={[-10.985, -2.933, -0.045]} rotation={[3.102, -0.078, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube77_aiStandardSurface2_0/></group>
                    <group name="pCube78" position={[-10.972, -3.029, -0.045]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube78_aiStandardSurface2_0/></group>
                    <group name="pCube79" position={[-10.97, -3.127, -0.044]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube79_aiStandardSurface2_0/></group>
                    <group name="pCube80" position={[-10.964, -3.233, -0.039]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube80_aiStandardSurface2_0/></group>
                    <group name="pCube81" position={[-10.952, -3.333, -0.039]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube81_aiStandardSurface2_0/></group>
                    <group name="pCube82" position={[-10.95, -3.43, -0.038]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube82_aiStandardSurface2_0/></group>
                    <group name="pCube83" position={[-10.941, -3.533, -0.036]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube83_aiStandardSurface2_0/></group>
                    <group name="pCube84" position={[-10.93, -3.634, -0.035]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube84_aiStandardSurface2_0/></group>
                    <group name="pCube85" position={[-10.925, -3.739, -0.035]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube85_aiStandardSurface2_0/></group>
                    <group name="pCube86" position={[-10.909, -3.845, -0.036]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube86_aiStandardSurface2_0/></group>
                    <group name="pCube87" position={[-10.913, -3.954, -0.028]} rotation={[3.101, -0.088, -0.066]} scale={[0.523, 0.047, 0.034]}><instances.pCube87_aiStandardSurface2_0/></group>
                    <group name="pCube88" position={[-10.927, -4.059, -0.004]} rotation={[1.62, 0.058, -0.018]} scale={[0.506, 0.013, 0.034]}><instances.pCube88_aiStandardSurface2_0/></group>
                    <group name="pCube89" position={[-11.264, 4.025, 0.03]} rotation={[-0.26, -0.044, 3.078]} scale={[-0.536, 0.047, 0.034]}><instances.pCube89_aiStandardSurface2_0/></group>
                    <group name="pCube90" position={[-11.265, 3.947, 0.054]} rotation={[-0.305, -0.052, 3.123]} scale={[-0.536, 0.047, 0.034]}><instances.pCube90_aiStandardSurface2_0/></group>
                    <group name="pCube91" position={[-11.27, 3.855, 0.075]} rotation={[-0.185, -0.064, 3.116]} scale={[-0.536, 0.047, 0.034]}><instances.pCube91_aiStandardSurface2_0/></group>
                    <group name="pCube92" position={[-11.274, 3.758, 0.091]} rotation={[-0.113, -0.077, 3.12]} scale={[-0.536, 0.047, 0.034]}><instances.pCube92_aiStandardSurface2_0/></group>
                    <group name="pCube93" position={[-11.292, 3.669, 0.098]} rotation={[-0.113, -0.077, 3.12]} scale={[-0.536, 0.047, 0.034]}><instances.pCube93_aiStandardSurface2_0/></group>
                    <group name="pCube94" position={[-11.296, 3.572, 0.105]} rotation={[-0.113, -0.077, 3.12]} scale={[-0.536, 0.047, 0.034]}><instances.pCube94_aiStandardSurface2_0/></group>
                    <group name="pCube95" position={[-11.303, 3.476, 0.114]} rotation={[-0.06, -0.082, 3.114]} scale={[-0.536, 0.047, 0.034]}><instances.pCube95_aiStandardSurface2_0/></group>
                    <group name="pCube96" position={[-11.315, 3.377, 0.117]} rotation={[-0.06, -0.082, 3.114]} scale={[-0.536, 0.047, 0.034]}><instances.pCube96_aiStandardSurface2_0/></group>
                    <group name="pCube97" position={[-11.32, 3.283, 0.12]} rotation={[0.011, -0.084, 3.107]} scale={[-0.536, 0.047, 0.034]}><instances.pCube97_aiStandardSurface2_0/></group>
                    <group name="pCube98" position={[-11.328, 3.185, 0.12]} rotation={[0.011, -0.084, 3.107]} scale={[-0.536, 0.047, 0.034]}><instances.pCube98_aiStandardSurface2_0/></group>
                    <group name="pCube99" position={[-11.336, 3.082, 0.119]} rotation={[0.011, -0.084, 3.107]} scale={[-0.536, 0.047, 0.034]}><instances.pCube99_aiStandardSurface2_0/></group>
                    <group name="pCube100" position={[-11.342, 2.982, 0.114]} rotation={[0.011, -0.084, 3.107]} scale={[-0.536, 0.047, 0.034]}><instances.pCube100_aiStandardSurface2_0/></group>
                    <group name="pCube101" position={[-11.339, 2.879, 0.109]} rotation={[0.011, -0.084, 3.107]} scale={[-0.536, 0.047, 0.034]}><instances.pCube101_aiStandardSurface2_0/></group>
                    <group name="pCube102" position={[-11.341, 2.778, 0.104]} rotation={[0.011, -0.084, 3.107]} scale={[-0.536, 0.047, 0.034]}><instances.pCube102_aiStandardSurface2_0/></group>
                    <group name="pCube103" position={[-11.343, 2.682, 0.099]} rotation={[0.011, -0.084, 3.107]} scale={[-0.536, 0.047, 0.034]}><instances.pCube103_aiStandardSurface2_0/></group>
                    <group name="pCube104" position={[-11.353, 2.584, 0.093]} rotation={[0.056, -0.096, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube104_aiStandardSurface2_0/></group>
                    <group name="pCube105" position={[-11.34, 2.482, 0.089]} rotation={[0.056, -0.096, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube105_aiStandardSurface2_0/></group>
                    <group name="pCube106" position={[-11.339, 2.384, 0.081]} rotation={[0.056, -0.096, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube106_aiStandardSurface2_0/></group>
                    <group name="pCube107" position={[-11.337, 2.284, 0.076]} rotation={[0.056, -0.096, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube107_aiStandardSurface2_0/></group>
                    <group name="pCube108" position={[-11.328, 2.184, 0.07]} rotation={[0.056, -0.096, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube108_aiStandardSurface2_0/></group>
                    <group name="pCube109" position={[-11.328, 2.088, 0.061]} rotation={[0.057, -0.09, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube109_aiStandardSurface2_0/></group>
                    <group name="pCube110" position={[-11.322, 1.987, 0.055]} rotation={[0.057, -0.09, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube110_aiStandardSurface2_0/></group>
                    <group name="pCube111" position={[-11.311, 1.885, 0.049]} rotation={[0.057, -0.09, 3.103]} scale={[-0.536, 0.047, 0.034]}><instances.pCube111_aiStandardSurface2_0/></group>
                    <group name="pCube112" position={[-11.302, 1.777, 0.038]} rotation={[0.064, -0.09, -3.141]} scale={[-0.536, 0.047, 0.034]}><instances.pCube112_aiStandardSurface2_0/></group>
                    <group name="pCube113" position={[-11.292, 1.677, 0.036]} rotation={[0.064, -0.09, -3.141]} scale={[-0.536, 0.047, 0.034]}><instances.pCube113_aiStandardSurface2_0/></group>
                    <group name="pCube114" position={[-11.279, 1.576, 0.029]} rotation={[0.064, -0.09, -3.141]} scale={[-0.536, 0.047, 0.034]}><instances.pCube114_aiStandardSurface2_0/></group>
                    <group name="pCube115" position={[-11.269, 1.473, 0.024]} rotation={[0.064, -0.09, -3.141]} scale={[-0.536, 0.047, 0.034]}><instances.pCube115_aiStandardSurface2_0/></group>
                    <group name="pCube116" position={[-11.252, 1.368, 0.017]} rotation={[0.064, -0.09, -3.141]} scale={[-0.536, 0.047, 0.034]}><instances.pCube116_aiStandardSurface2_0/></group>
                    <group name="pCube117" position={[-11.248, 1.269, 0.01]} rotation={[0.064, -0.09, -3.141]} scale={[-0.536, 0.047, 0.034]}><instances.pCube117_aiStandardSurface2_0/></group>
                    <group name="pCube118" position={[-11.236, 1.163, 0.002]} rotation={[0.071, -0.09, -3.099]} scale={[-0.536, 0.047, 0.034]}><instances.pCube118_aiStandardSurface2_0/></group>
                    <group name="pCube119" position={[-11.216, 1.061, -0.003]} rotation={[0.071, -0.09, -3.099]} scale={[-0.536, 0.047, 0.034]}><instances.pCube119_aiStandardSurface2_0/></group>
                    <group name="pCube120" position={[-11.196, 0.962, -0.011]} rotation={[0.076, -0.09, -3.068]} scale={[-0.536, 0.047, 0.034]}><instances.pCube120_aiStandardSurface2_0/></group>
                    <group name="pCube121" position={[-11.172, 0.866, -0.015]} rotation={[0.073, -0.09, -3.087]} scale={[-0.536, 0.047, 0.034]}><instances.pCube121_aiStandardSurface2_0/></group>
                    <group name="pCube122" position={[-11.155, 0.765, -0.023]} rotation={[0.073, -0.09, -3.087]} scale={[-0.536, 0.047, 0.034]}><instances.pCube122_aiStandardSurface2_0/></group>
                    <group name="pCube123" position={[-11.128, 0.666, -0.029]} rotation={[0.073, -0.09, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube123_aiStandardSurface2_0/></group>
                    <group name="pCube124" position={[-11.103, 0.568, -0.032]} rotation={[0.073, -0.09, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube124_aiStandardSurface2_0/></group>
                    <group name="pCube125" position={[-11.08, 0.474, -0.037]} rotation={[0.073, -0.08, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube125_aiStandardSurface2_0/></group>
                    <group name="pCube126" position={[-11.053, 0.376, -0.042]} rotation={[0.073, -0.08, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube126_aiStandardSurface2_0/></group>
                    <group name="pCube127" position={[-11.026, 0.278, -0.045]} rotation={[0.073, -0.088, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube127_aiStandardSurface2_0/></group>
                    <group name="pCube128" position={[-11.003, 0.183, -0.051]} rotation={[0.072, -0.078, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube128_aiStandardSurface2_0/></group>
                    <group name="pCube129" position={[-10.983, 0.086, -0.054]} rotation={[0.072, -0.078, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube129_aiStandardSurface2_0/></group>
                    <group name="pCube130" position={[-10.972, -0.013, -0.057]} rotation={[0.072, -0.077, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube130_aiStandardSurface2_0/></group>
                    <group name="pCube131" position={[-10.955, -0.112, -0.059]} rotation={[0.072, -0.079, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube131_aiStandardSurface2_0/></group>
                    <group name="pCube132" position={[-10.939, -0.209, -0.062]} rotation={[0.072, -0.079, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube132_aiStandardSurface2_0/></group>
                    <group name="pCube133" position={[-10.924, -0.31, -0.063]} rotation={[0.072, -0.078, -3.087]} scale={[-0.512, 0.047, 0.034]}><instances.pCube133_aiStandardSurface2_0/></group>
                    <group name="pCube134" position={[-10.918, -0.413, -0.06]} rotation={[-0.007, -0.083, -3.08]} scale={[-0.512, 0.047, 0.034]}><instances.pCube134_aiStandardSurface2_0/></group>
                    <group name="pCube135" position={[-10.914, -0.512, -0.06]} rotation={[-0.007, -0.084, -3.08]} scale={[-0.512, 0.047, 0.034]}><instances.pCube135_aiStandardSurface2_0/></group>
                    <group name="pCube136" position={[-10.913, -0.612, -0.06]} rotation={[-0.007, -0.082, -3.08]} scale={[-0.512, 0.047, 0.034]}><instances.pCube136_aiStandardSurface2_0/></group>
                    <group name="pCube137" position={[-10.911, -0.71, -0.061]} rotation={[-0.007, -0.082, -3.08]} scale={[-0.512, 0.047, 0.034]}><instances.pCube137_aiStandardSurface2_0/></group>
                    <group name="pCube138" position={[-10.912, -0.805, -0.058]} rotation={[-0.012, -0.083, -3.11]} scale={[-0.523, 0.047, 0.034]}><instances.pCube138_aiStandardSurface2_0/></group>
                    <group name="pCube139" position={[-10.917, -0.899, -0.055]} rotation={[-0.015, -0.083, -3.13]} scale={[-0.523, 0.047, 0.034]}><instances.pCube139_aiStandardSurface2_0/></group>
                    <group name="pCube140" position={[-10.929, -1, -0.053]} rotation={[-0.015, -0.082, -3.13]} scale={[-0.523, 0.047, 0.034]}><instances.pCube140_aiStandardSurface2_0/></group>
                    <group name="pCube141" position={[-10.935, -1.1, -0.048]} rotation={[-0.015, -0.084, -3.13]} scale={[-0.523, 0.047, 0.034]}><instances.pCube141_aiStandardSurface2_0/></group>
                    <group name="pCube142" position={[-10.948, -1.2, -0.043]} rotation={[-0.017, -0.083, -3.141]} scale={[-0.523, 0.047, 0.034]}><instances.pCube142_aiStandardSurface2_0/></group>
                    <group name="pCube143" position={[-10.957, -1.299, -0.038]} rotation={[-0.02, -0.083, 3.125]} scale={[-0.523, 0.047, 0.034]}><instances.pCube143_aiStandardSurface2_0/></group>
                    <group name="pCube144" position={[-10.967, -1.4, -0.034]} rotation={[-0.022, -0.082, 3.113]} scale={[-0.523, 0.047, 0.034]}><instances.pCube144_aiStandardSurface2_0/></group>
                    <group name="pCube145" position={[-10.975, -1.504, -0.029]} rotation={[-0.024, -0.083, 3.101]} scale={[-0.523, 0.047, 0.034]}><instances.pCube145_aiStandardSurface2_0/></group>
                    <group name="pCube146" position={[-10.981, -1.601, -0.023]} rotation={[-0.026, -0.083, 3.09]} scale={[-0.523, 0.047, 0.034]}><instances.pCube146_aiStandardSurface2_0/></group>
                    <group name="pCube147" position={[-10.994, -1.701, -0.019]} rotation={[-0.026, -0.083, 3.09]} scale={[-0.523, 0.047, 0.034]}><instances.pCube147_aiStandardSurface2_0/></group>
                    <group name="pCube148" position={[-11.001, -1.799, -0.016]} rotation={[-0.026, -0.083, 3.09]} scale={[-0.523, 0.047, 0.034]}><instances.pCube148_aiStandardSurface2_0/></group>
                    <group name="pCube149" position={[-11.012, -1.897, -0.01]} rotation={[-0.026, -0.083, 3.09]} scale={[-0.523, 0.047, 0.034]}><instances.pCube149_aiStandardSurface2_0/></group>
                    <group name="pCube150" position={[-11.021, -1.991, -0.006]} rotation={[-0.026, -0.083, 3.09]} scale={[-0.523, 0.047, 0.034]}><instances.pCube150_aiStandardSurface2_0/></group>
                    <group name="pCube151" position={[-11.023, -2.096, -0.002]} rotation={[-0.021, -0.083, 3.118]} scale={[-0.523, 0.047, 0.034]}><instances.pCube151_aiStandardSurface2_0/></group>
                    <group name="pCube152" position={[-11.019, -2.204, 0.002]} rotation={[-0.018, -0.093, 3.139]} scale={[-0.523, 0.047, 0.034]}><instances.pCube152_aiStandardSurface2_0/></group>
                    <group name="pCube153" position={[-11.016, -2.303, 0.006]} rotation={[-0.018, -0.093, 3.139]} scale={[-0.523, 0.047, 0.034]}><instances.pCube153_aiStandardSurface2_0/></group>
                    <group name="pCube154" position={[-11.014, -2.406, 0.009]} rotation={[-0.018, -0.093, 3.139]} scale={[-0.523, 0.047, 0.034]}><instances.pCube154_aiStandardSurface2_0/></group>
                    <group name="pCube155" position={[-11.012, -2.51, 0.014]} rotation={[-0.016, -0.093, -3.132]} scale={[-0.523, 0.047, 0.034]}><instances.pCube155_aiStandardSurface2_0/></group>
                    <group name="pCube156" position={[-11.011, -2.62, 0.017]} rotation={[-0.033, -0.099, -3.104]} scale={[-0.523, 0.047, 0.034]}><instances.pCube156_aiStandardSurface2_0/></group>
                    <group name="pCube157" position={[-11.004, -2.722, 0.02]} rotation={[-0.03, -0.099, -3.089]} scale={[-0.523, 0.047, 0.034]}><instances.pCube157_aiStandardSurface2_0/></group>
                    <group name="pCube158" position={[-10.996, -2.833, 0.022]} rotation={[-0.028, -0.099, -3.075]} scale={[-0.523, 0.047, 0.034]}><instances.pCube158_aiStandardSurface2_0/></group>
                    <group name="pCube159" position={[-10.988, -2.933, 0.024]} rotation={[-0.028, -0.09, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube159_aiStandardSurface2_0/></group>
                    <group name="pCube160" position={[-10.97, -3.029, 0.027]} rotation={[-0.029, -0.08, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube160_aiStandardSurface2_0/></group>
                    <group name="pCube161" position={[-10.969, -3.127, 0.029]} rotation={[-0.029, -0.088, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube161_aiStandardSurface2_0/></group>
                    <group name="pCube162" position={[-10.963, -3.233, 0.032]} rotation={[-0.029, -0.088, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube162_aiStandardSurface2_0/></group>
                    <group name="pCube163" position={[-10.952, -3.333, 0.032]} rotation={[-0.029, -0.088, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube163_aiStandardSurface2_0/></group>
                    <group name="pCube164" position={[-10.946, -3.43, 0.034]} rotation={[-0.029, -0.088, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube164_aiStandardSurface2_0/></group>
                    <group name="pCube165" position={[-10.93, -3.533, 0.036]} rotation={[-0.029, -0.088, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube165_aiStandardSurface2_0/></group>
                    <group name="pCube166" position={[-10.931, -3.634, 0.035]} rotation={[-0.029, -0.088, -3.076]} scale={[-0.523, 0.047, 0.034]}><instances.pCube166_aiStandardSurface2_0/></group>
                    <group name="pCube167" position={[-10.918, -3.739, 0.035]} rotation={[0.032, -0.084, -3.07]} scale={[-0.523, 0.047, 0.034]}><instances.pCube167_aiStandardSurface2_0/></group>
                    <group name="pCube168" position={[-10.914, -3.845, 0.034]} rotation={[0.017, -0.085, -3.072]} scale={[-0.523, 0.047, 0.034]}><instances.pCube168_aiStandardSurface2_0/></group>
                    <group name="pCube169" position={[-10.909, -3.954, 0.03]} rotation={[0.068, -0.084, -3.067]} scale={[-0.523, 0.047, 0.034]}><instances.pCube169_aiStandardSurface2_0/></group>
                  </group>
                  <group name="group3" userData={{ name: 'group3' }}>
                    <group name="pCube170" position={[11.795, 3.458, 0.033]} rotation={[-0.107, 0.075, -3.134]} scale={[-0.71, 0.047, 0.034]}><instances.pCube170_aiStandardSurface3_0/></group>
                    <group name="pCube171" position={[11.81, 3.382, 0.041]} rotation={[-0.107, 0.085, -3.134]} scale={[-0.71, 0.047, 0.034]}><instances.pCube171_aiStandardSurface3_0/></group>
                    <group name="pCube172" position={[11.814, 3.301, 0.042]} rotation={[-0.009, 0.085, 3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube172_aiStandardSurface3_0/></group>
                    <group name="pCube173" position={[11.825, 3.212, 0.04]} rotation={[0.019, 0.096, 3.139]} scale={[-0.71, 0.047, 0.034]}><instances.pCube173_aiStandardSurface3_0/></group>
                    <group name="pCube174" position={[11.835, 3.108, 0.04]} rotation={[0.02, 0.096, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube174_aiStandardSurface3_0/></group>
                    <group name="pCube175" position={[11.847, 3.005, 0.032]} rotation={[0.02, 0.096, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube175_aiStandardSurface3_0/></group>
                    <group name="pCube176" position={[11.858, 2.906, 0.03]} rotation={[0.02, 0.096, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube176_aiStandardSurface3_0/></group>
                    <group name="pCube177" position={[11.865, 2.808, 0.025]} rotation={[0.02, 0.096, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube177_aiStandardSurface3_0/></group>
                    <group name="pCube178" position={[11.864, 2.71, 0.02]} rotation={[0.02, 0.096, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube178_aiStandardSurface3_0/></group>
                    <group name="pCube179" position={[11.881, 2.605, 0.01]} rotation={[0.02, 0.078, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube179_aiStandardSurface3_0/></group>
                    <group name="pCube180" position={[11.889, 2.514, 0.01]} rotation={[0.02, 0.089, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube180_aiStandardSurface3_0/></group>
                    <group name="pCube181" position={[11.886, 2.419, 0.01]} rotation={[0.02, 0.089, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube181_aiStandardSurface3_0/></group>
                    <group name="pCube182" position={[11.886, 2.321, 0.01]} rotation={[0.02, 0.089, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube182_aiStandardSurface3_0/></group>
                    <group name="pCube183" position={[11.886, 2.227, 0.008]} rotation={[0.02, 0.089, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube183_aiStandardSurface3_0/></group>
                    <group name="pCube184" position={[11.886, 2.122, 0.006]} rotation={[0.02, 0.089, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube184_aiStandardSurface3_0/></group>
                    <group name="pCube185" position={[11.884, 2.025, 0.008]} rotation={[0.02, 0.077, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube185_aiStandardSurface3_0/></group>
                    <group name="pCube186" position={[11.878, 1.924, 0.008]} rotation={[0.02, 0.075, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube186_aiStandardSurface3_0/></group>
                    <group name="pCube187" position={[11.872, 1.821, 0.011]} rotation={[-0.062, 0.075, -3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube187_aiStandardSurface3_0/></group>
                    <group name="pCube188" position={[11.866, 1.729, 0.015]} rotation={[-0.062, 0.075, -3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube188_aiStandardSurface3_0/></group>
                    <group name="pCube189" position={[11.862, 1.627, 0.018]} rotation={[0.011, 0.075, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube189_aiStandardSurface3_0/></group>
                    <group name="pCube190" position={[11.856, 1.535, 0.02]} rotation={[0.011, 0.075, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube190_aiStandardSurface3_0/></group>
                    <group name="pCube191" position={[11.849, 1.435, 0.024]} rotation={[-0.018, 0.075, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube191_aiStandardSurface3_0/></group>
                    <group name="pCube192" position={[11.836, 1.337, 0.027]} rotation={[-0.018, 0.064, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube192_aiStandardSurface3_0/></group>
                    <group name="pCube193" position={[11.836, 1.243, 0.028]} rotation={[-0.018, 0.064, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube193_aiStandardSurface3_0/></group>
                    <group name="pCube194" position={[11.817, 1.144, 0.036]} rotation={[-0.018, 0.075, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube194_aiStandardSurface3_0/></group>
                    <group name="pCube195" position={[11.815, 1.045, 0.038]} rotation={[-0.018, 0.07, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube195_aiStandardSurface3_0/></group>
                    <group name="pCube196" position={[11.815, 0.944, 0.04]} rotation={[-0.018, 0.07, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube196_aiStandardSurface3_0/></group>
                    <group name="pCube197" position={[11.807, 0.851, 0.045]} rotation={[-0.018, 0.07, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube197_aiStandardSurface3_0/></group>
                    <group name="pCube198" position={[11.803, 0.763, 0.045]} rotation={[-0.018, 0.061, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube198_aiStandardSurface3_0/></group>
                    <group name="pCube199" position={[11.803, 0.672, 0.048]} rotation={[-0.018, 0.066, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube199_aiStandardSurface3_0/></group>
                    <group name="pCube200" position={[11.799, 0.58, 0.05]} rotation={[-0.018, 0.061, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube200_aiStandardSurface3_0/></group>
                    <group name="pCube201" position={[11.79, 0.478, 0.051]} rotation={[-0.018, 0.056, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube201_aiStandardSurface3_0/></group>
                    <group name="pCube202" position={[11.785, 0.369, 0.055]} rotation={[-0.031, 0.061, -3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube202_aiStandardSurface3_0/></group>
                    <group name="pCube203" position={[11.783, 0.257, 0.058]} rotation={[-0.031, 0.061, -3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube203_aiStandardSurface3_0/></group>
                    <group name="pCube204" position={[11.775, 0.155, 0.061]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube204_aiStandardSurface3_0/></group>
                    <group name="pCube205" position={[11.775, 0.057, 0.063]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube205_aiStandardSurface3_0/></group>
                    <group name="pCube206" position={[11.775, -0.043, 0.063]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube206_aiStandardSurface3_0/></group>
                    <group name="pCube207" position={[11.771, -0.148, 0.065]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube207_aiStandardSurface3_0/></group>
                    <group name="pCube208" position={[11.768, -0.251, 0.065]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube208_aiStandardSurface3_0/></group>
                    <group name="pCube209" position={[11.768, -0.345, 0.065]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube209_aiStandardSurface3_0/></group>
                    <group name="pCube210" position={[11.763, -0.449, 0.065]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube210_aiStandardSurface3_0/></group>
                    <group name="pCube211" position={[11.763, -0.543, 0.065]} rotation={[-0.055, 0.061, -3.138]} scale={[-0.71, 0.047, 0.034]}><instances.pCube211_aiStandardSurface3_0/></group>
                    <group name="pCube212" position={[11.761, -0.644, 0.065]} rotation={[-0.055, 0.056, -3.139]} scale={[-0.71, 0.047, 0.034]}><instances.pCube212_aiStandardSurface2_0/></group>
                    <group name="pCube213" position={[11.761, -0.75, 0.065]} rotation={[-0.055, 0.056, -3.139]} scale={[-0.71, 0.047, 0.034]}><instances.pCube213_aiStandardSurface2_0/></group>
                    <group name="pCube214" position={[11.761, -0.85, 0.065]} rotation={[-0.009, 0.056, -3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube214_aiStandardSurface2_0/></group>
                    <group name="pCube215" position={[11.761, -0.953, 0.065]} rotation={[-0.034, 0.058, -3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube215_aiStandardSurface2_0/></group>
                    <group name="pCube216" position={[11.761, -1.059, 0.065]} rotation={[0.006, 0.058, 3.141]} scale={[-0.71, 0.047, 0.034]}><instances.pCube216_aiStandardSurface2_0/></group>
                    <group name="pCube217" position={[11.761, -1.158, 0.065]} rotation={[0.03, 0.058, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube217_aiStandardSurface2_0/></group>
                    <group name="pCube218" position={[11.761, -1.263, 0.065]} rotation={[0.024, 0.058, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube218_aiStandardSurface2_0/></group>
                    <group name="pCube219" position={[11.761, -1.362, 0.065]} rotation={[0.024, 0.059, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube219_aiStandardSurface2_0/></group>
                    <group name="pCube220" position={[11.761, -1.457, 0.065]} rotation={[0.024, 0.059, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube220_aiStandardSurface2_0/></group>
                    <group name="pCube221" position={[11.761, -1.551, 0.065]} rotation={[0.024, 0.059, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube221_aiStandardSurface2_0/></group>
                    <group name="pCube222" position={[11.761, -1.636, 0.065]} rotation={[0.024, 0.059, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube222_aiStandardSurface2_0/></group>
                    <group name="pCube223" position={[11.761, -1.72, 0.065]} rotation={[0.024, 0.059, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube223_aiStandardSurface2_0/></group>
                    <group name="pCube224" position={[11.761, -1.8, 0.063]} rotation={[0.024, 0.059, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube224_aiStandardSurface2_0/></group>
                    <group name="pCube225" position={[11.761, -1.89, 0.063]} rotation={[0.024, 0.059, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube225_aiStandardSurface2_0/></group>
                    <group name="pCube226" position={[11.777, -1.977, 0.062]} rotation={[0.024, 0.071, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube226_aiStandardSurface2_0/></group>
                    <group name="pCube227" position={[11.773, -2.068, 0.062]} rotation={[0.024, 0.071, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube227_aiStandardSurface2_0/></group>
                    <group name="pCube228" position={[11.783, -2.161, 0.061]} rotation={[0.024, 0.079, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube228_aiStandardSurface2_0/></group>
                    <group name="pCube229" position={[11.785, -2.253, 0.061]} rotation={[0.025, 0.084, 3.14]} scale={[-0.71, 0.047, 0.034]}><instances.pCube229_aiStandardSurface2_0/></group>
                    <group name="pCube230" position={[11.796, -2.353, 0.054]} rotation={[0.049, 0.091, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube230_aiStandardSurface2_0/></group>
                    <group name="pCube231" position={[11.802, -2.451, 0.045]} rotation={[0.049, 0.091, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube231_aiStandardSurface2_0/></group>
                    <group name="pCube232" position={[11.821, -2.546, 0.039]} rotation={[0.049, 0.091, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube232_aiStandardSurface2_0/></group>
                    <group name="pCube233" position={[11.833, -2.647, 0.031]} rotation={[0.049, 0.091, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube233_aiStandardSurface2_0/></group>
                    <group name="pCube234" position={[11.843, -2.748, 0.024]} rotation={[0.049, 0.096, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube234_aiStandardSurface2_0/></group>
                    <group name="pCube235" position={[11.859, -2.848, 0.014]} rotation={[0.049, 0.096, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube235_aiStandardSurface2_0/></group>
                    <group name="pCube236" position={[11.869, -2.945, 0.006]} rotation={[0.049, 0.096, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube236_aiStandardSurface2_0/></group>
                    <group name="pCube237" position={[11.888, -3.044, -0.007]} rotation={[0.049, 0.096, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube237_aiStandardSurface2_0/></group>
                    <group name="pCube238" position={[11.898, -3.139, -0.015]} rotation={[0.049, 0.096, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube238_aiStandardSurface2_0/></group>
                    <group name="pCube239" position={[11.915, -3.245, -0.025]} rotation={[0.049, 0.096, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube239_aiStandardSurface2_0/></group>
                    <group name="pCube240" position={[11.93, -3.346, -0.034]} rotation={[0.049, 0.101, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube240_aiStandardSurface3_0/></group>
                    <group name="pCube241" position={[11.941, -3.442, -0.045]} rotation={[0.049, 0.101, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube241_aiStandardSurface3_0/></group>
                    <group name="pCube242" position={[11.956, -3.533, -0.053]} rotation={[0.049, 0.105, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube242_aiStandardSurface3_0/></group>
                    <group name="pCube243" position={[11.967, -3.622, -0.059]} rotation={[0.049, 0.105, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube243_aiStandardSurface3_0/></group>
                    <group name="pCube244" position={[11.982, -3.726, -0.068]} rotation={[0.049, 0.105, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube244_aiStandardSurface3_0/></group>
                    <group name="pCube245" position={[11.995, -3.828, -0.077]} rotation={[0.049, 0.105, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube245_aiStandardSurface3_0/></group>
                    <group name="pCube246" position={[12.013, -3.928, -0.09]} rotation={[0.049, 0.105, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube246_aiStandardSurface3_0/></group>
                    <group name="pCube247" position={[12.025, -4.032, -0.097]} rotation={[0.049, 0.087, 3.137]} scale={[-0.71, 0.047, 0.034]}><instances.pCube247_aiStandardSurface3_0/></group>
                    <group name="pCube248" position={[12.025, -4.132, -0.108]} rotation={[0.177, 0.086, 3.126]} scale={[-0.71, 0.047, 0.034]}><instances.pCube248_aiStandardSurface3_0/></group>
                    <group name="pCube249" position={[11.795, 3.458, -0.036]} rotation={[-3.04, 0.088, -0.019]} scale={[0.71, 0.047, 0.034]}><instances.pCube249_aiStandardSurface3_0/></group>
                    <group name="pCube250" position={[11.81, 3.382, -0.039]} rotation={[-3.081, 0.087, -0.023]} scale={[0.71, 0.047, 0.034]}><instances.pCube250_aiStandardSurface3_0/></group>
                    <group name="pCube251" position={[11.814, 3.301, -0.043]} rotation={[-3.118, 0.089, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube251_aiStandardSurface3_0/></group>
                    <group name="pCube252" position={[11.825, 3.212, -0.05]} rotation={[-3.095, 0.087, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube252_aiStandardSurface3_0/></group>
                    <group name="pCube253" position={[11.835, 3.112, -0.057]} rotation={[-3.065, 0.092, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube253_aiStandardSurface3_0/></group>
                    <group name="pCube254" position={[11.847, 3.021, -0.063]} rotation={[-3.085, 0.104, -0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube254_aiStandardSurface3_0/></group>
                    <group name="pCube255" position={[11.858, 2.921, -0.063]} rotation={[-3.08, 0.089, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube255_aiStandardSurface3_0/></group>
                    <group name="pCube256" position={[11.865, 2.824, -0.069]} rotation={[-3.087, 0.1, -0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube256_aiStandardSurface3_0/></group>
                    <group name="pCube257" position={[11.864, 2.726, -0.07]} rotation={[-3.08, 0.078, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube257_aiStandardSurface3_0/></group>
                    <group name="pCube258" position={[11.881, 2.637, -0.077]} rotation={[-3.096, 0.096, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube258_aiStandardSurface3_0/></group>
                    <group name="pCube259" position={[11.889, 2.546, -0.076]} rotation={[-3.122, 0.085, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube259_aiStandardSurface3_0/></group>
                    <group name="pCube260" position={[11.886, 2.448, -0.077]} rotation={[-3.122, 0.085, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube260_aiStandardSurface3_0/></group>
                    <group name="pCube261" position={[11.886, 2.342, -0.074]} rotation={[-3.122, 0.085, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube261_aiStandardSurface3_0/></group>
                    <group name="pCube262" position={[11.886, 2.244, -0.073]} rotation={[3.131, 0.085, 0.004]} scale={[0.71, 0.047, 0.034]}><instances.pCube262_aiStandardSurface3_0/></group>
                    <group name="pCube263" position={[11.886, 2.146, -0.069]} rotation={[3.085, 0.085, 0.008]} scale={[0.71, 0.047, 0.034]}><instances.pCube263_aiStandardSurface3_0/></group>
                    <group name="pCube264" position={[11.881, 2.053, -0.062]} rotation={[-3.122, 0.097, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube264_aiStandardSurface3_0/></group>
                    <group name="pCube265" position={[11.874, 1.965, -0.061]} rotation={[3.112, 0.099, 0.007]} scale={[0.71, 0.047, 0.034]}><instances.pCube265_aiStandardSurface3_0/></group>
                    <group name="pCube266" position={[11.87, 1.859, -0.052]} rotation={[3.08, 0.09, -0.004]} scale={[0.71, 0.047, 0.034]}><instances.pCube266_aiStandardSurface3_0/></group>
                    <group name="pCube267" position={[11.866, 1.759, -0.052]} rotation={[3.08, 0.08, -0.004]} scale={[0.71, 0.047, 0.034]}><instances.pCube267_aiStandardSurface3_0/></group>
                    <group name="pCube268" position={[11.857, 1.656, -0.051]} rotation={[-3.131, 0.08, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube268_aiStandardSurface3_0/></group>
                    <group name="pCube269" position={[11.856, 1.55, -0.043]} rotation={[-3.131, 0.071, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube269_aiStandardSurface3_0/></group>
                    <group name="pCube270" position={[11.849, 1.438, -0.037]} rotation={[3.124, 0.07, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube270_aiStandardSurface3_0/></group>
                    <group name="pCube271" position={[11.836, 1.337, -0.034]} rotation={[3.124, 0.07, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube271_aiStandardSurface3_0/></group>
                    <group name="pCube272" position={[11.836, 1.243, -0.029]} rotation={[3.124, 0.069, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube272_aiStandardSurface3_0/></group>
                    <group name="pCube273" position={[11.817, 1.144, -0.023]} rotation={[3.124, 0.07, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube273_aiStandardSurface3_0/></group>
                    <group name="pCube274" position={[11.815, 1.045, -0.017]} rotation={[3.124, 0.082, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube274_aiStandardSurface3_0/></group>
                    <group name="pCube275" position={[11.811, 0.944, -0.016]} rotation={[3.124, 0.074, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube275_aiStandardSurface3_0/></group>
                    <group name="pCube276" position={[11.807, 0.851, -0.011]} rotation={[3.096, 0.063, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube276_aiStandardSurface3_0/></group>
                    <group name="pCube277" position={[11.803, 0.763, -0.008]} rotation={[3.124, 0.063, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube277_aiStandardSurface3_0/></group>
                    <group name="pCube278" position={[11.797, 0.672, -0.006]} rotation={[3.124, 0.066, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube278_aiStandardSurface3_0/></group>
                    <group name="pCube279" position={[11.792, 0.58, -0.002]} rotation={[3.124, 0.064, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube279_aiStandardSurface3_0/></group>
                    <group name="pCube280" position={[11.79, 0.478, 0.001]} rotation={[3.124, 0.068, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube280_aiStandardSurface3_0/></group>
                    <group name="pCube281" position={[11.781, 0.369, 0.003]} rotation={[3.111, 0.064, -0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube281_aiStandardSurface3_0/></group>
                    <group name="pCube282" position={[11.783, 0.257, 0.007]} rotation={[3.111, 0.064, -0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube282_aiStandardSurface3_0/></group>
                    <group name="pCube283" position={[11.775, 0.155, 0.008]} rotation={[3.087, 0.065, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube283_aiStandardSurface3_0/></group>
                    <group name="pCube284" position={[11.775, 0.057, 0.012]} rotation={[3.087, 0.064, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube284_aiStandardSurface3_0/></group>
                    <group name="pCube285" position={[11.775, -0.043, 0.015]} rotation={[3.087, 0.064, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube285_aiStandardSurface3_0/></group>
                    <group name="pCube286" position={[11.771, -0.148, 0.02]} rotation={[3.087, 0.054, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube286_aiStandardSurface3_0/></group>
                    <group name="pCube287" position={[11.768, -0.251, 0.016]} rotation={[3.087, 0.064, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube287_aiStandardSurface3_0/></group>
                    <group name="pCube288" position={[11.768, -0.345, 0.016]} rotation={[3.087, 0.064, -0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube288_aiStandardSurface3_0/></group>
                    <group name="pCube289" position={[11.763, -0.449, 0.015]} rotation={[-3.119, 0.065, -0.008]} scale={[0.71, 0.047, 0.034]}><instances.pCube289_aiStandardSurface3_0/></group>
                    <group name="pCube290" position={[11.761, -0.543, 0.015]} rotation={[-3.122, 0.066, -0.012]} scale={[0.71, 0.047, 0.034]}><instances.pCube290_aiStandardSurface3_0/></group>
                    <group name="pCube291" position={[11.761, -0.644, 0.018]} rotation={[3.131, 0.058, -0.005]} scale={[0.71, 0.047, 0.034]}><instances.pCube291_aiStandardSurface3_0/></group>
                    <group name="pCube292" position={[11.761, -0.75, 0.019]} rotation={[3.139, 0.055, -0.009]} scale={[0.71, 0.047, 0.034]}><instances.pCube292_aiStandardSurface3_0/></group>
                    <group name="pCube293" position={[11.761, -0.85, 0.018]} rotation={[3.132, 0.055, 0]} scale={[0.71, 0.047, 0.034]}><instances.pCube293_aiStandardSurface3_0/></group>
                    <group name="pCube294" position={[11.761, -0.953, 0.016]} rotation={[3.108, 0.068, -0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube294_aiStandardSurface3_0/></group>
                    <group name="pCube295" position={[11.754, -1.059, 0.011]} rotation={[-3.136, 0.067, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube295_aiStandardSurface3_0/></group>
                    <group name="pCube296" position={[11.757, -1.158, 0.014]} rotation={[-3.112, 0.057, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube296_aiStandardSurface3_0/></group>
                    <group name="pCube297" position={[11.761, -1.263, 0.014]} rotation={[-3.117, 0.055, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube297_aiStandardSurface3_0/></group>
                    <group name="pCube298" position={[11.759, -1.362, 0.012]} rotation={[-3.117, 0.063, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube298_aiStandardSurface3_0/></group>
                    <group name="pCube299" position={[11.758, -1.457, 0.009]} rotation={[-3.117, 0.073, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube299_aiStandardSurface3_0/></group>
                    <group name="pCube300" position={[11.761, -1.551, 0.008]} rotation={[-3.117, 0.07, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube300_aiStandardSurface3_0/></group>
                    <group name="pCube301" position={[11.761, -1.636, 0.005]} rotation={[-3.117, 0.076, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube301_aiStandardSurface3_0/></group>
                    <group name="pCube302" position={[11.761, -1.72, 0.003]} rotation={[-3.117, 0.075, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube302_aiStandardSurface3_0/></group>
                    <group name="pCube303" position={[11.761, -1.8, -0.001]} rotation={[-3.117, 0.073, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube303_aiStandardSurface3_0/></group>
                    <group name="pCube304" position={[11.761, -1.89, -0.003]} rotation={[-3.117, 0.085, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube304_aiStandardSurface3_0/></group>
                    <group name="pCube305" position={[11.777, -1.977, -0.004]} rotation={[-3.117, 0.074, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube305_aiStandardSurface3_0/></group>
                    <group name="pCube306" position={[11.773, -2.068, -0.014]} rotation={[-3.117, 0.083, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube306_aiStandardSurface3_0/></group>
                    <group name="pCube307" position={[11.783, -2.161, -0.015]} rotation={[-3.117, 0.076, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube307_aiStandardSurface3_0/></group>
                    <group name="pCube308" position={[11.785, -2.253, -0.02]} rotation={[-3.117, 0.091, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube308_aiStandardSurface3_0/></group>
                    <group name="pCube309" position={[11.796, -2.353, -0.03]} rotation={[-3.069, 0.084, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube309_aiStandardSurface3_0/></group>
                    <group name="pCube310" position={[11.807, -2.451, -0.042]} rotation={[-3.033, 0.084, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube310_aiStandardSurface3_0/></group>
                    <group name="pCube311" position={[11.821, -2.546, -0.049]} rotation={[-2.983, 0.084, -0.005]} scale={[0.71, 0.047, 0.034]}><instances.pCube311_aiStandardSurface3_0/></group>
                    <group name="pCube312" position={[11.833, -2.647, -0.061]} rotation={[-3.015, 0.084, -0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube312_aiStandardSurface3_0/></group>
                    <group name="pCube313" position={[11.843, -2.748, -0.065]} rotation={[-3.05, 0.079, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube313_aiStandardSurface3_0/></group>
                    <group name="pCube314" position={[11.854, -2.848, -0.081]} rotation={[-3.042, 0.093, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube314_aiStandardSurface3_0/></group>
                    <group name="pCube315" position={[11.869, -2.945, -0.09]} rotation={[-3.003, 0.089, -0.004]} scale={[0.71, 0.047, 0.034]}><instances.pCube315_aiStandardSurface3_0/></group>
                    <group name="pCube316" position={[11.883, -3.044, -0.099]} rotation={[-3, 0.09, -0.004]} scale={[0.71, 0.047, 0.034]}><instances.pCube316_aiStandardSurface3_0/></group>
                    <group name="pCube317" position={[11.898, -3.139, -0.112]} rotation={[-2.995, 0.092, -0.004]} scale={[0.71, 0.047, 0.034]}><instances.pCube317_aiStandardSurface3_0/></group>
                    <group name="pCube318" position={[11.908, -3.245, -0.122]} rotation={[-3.027, 0.108, -0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube318_aiStandardSurface3_0/></group>
                    <group name="pCube319" position={[11.927, -3.346, -0.138]} rotation={[-2.972, 0.093, -0.007]} scale={[0.71, 0.047, 0.034]}><instances.pCube319_aiStandardSurface3_0/></group>
                    <group name="pCube320" position={[11.941, -3.442, -0.149]} rotation={[-3.04, 0.095, 0]} scale={[0.71, 0.047, 0.034]}><instances.pCube320_aiStandardSurface3_0/></group>
                    <group name="pCube321" position={[11.956, -3.533, -0.153]} rotation={[-3.057, 0.09, 0.002]} scale={[0.71, 0.047, 0.034]}><instances.pCube321_aiStandardSurface3_0/></group>
                    <group name="pCube322" position={[11.967, -3.622, -0.16]} rotation={[-3.042, 0.08, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube322_aiStandardSurface3_0/></group>
                    <group name="pCube323" position={[11.982, -3.726, -0.169]} rotation={[-3.021, 0.09, 0]} scale={[0.71, 0.047, 0.034]}><instances.pCube323_aiStandardSurface3_0/></group>
                    <group name="pCube324" position={[11.995, -3.828, -0.177]} rotation={[-3.045, 0.092, 0.001]} scale={[0.71, 0.047, 0.034]}><instances.pCube324_aiStandardSurface3_0/></group>
                    <group name="pCube325" position={[12.013, -3.928, -0.185]} rotation={[-3.072, 0.092, 0.003]} scale={[0.71, 0.047, 0.034]}><instances.pCube325_aiStandardSurface3_0/></group>
                    <group name="pCube326" position={[12.021, -4.032, -0.185]} rotation={[-3.093, 0.087, 0.004]} scale={[0.71, 0.047, 0.034]}><instances.pCube326_aiStandardSurface3_0/></group>
                    <group name="pCube327" position={[12.025, -4.132, -0.177]} rotation={[2.953, 0.077, 0.046]} scale={[0.71, 0.047, 0.034]}><instances.pCube327_aiStandardSurface3_0/></group>
                    <group name="pCube328" position={[12.025, -4.214, -0.144]} rotation={[1.619, 0.046, 0.001]} scale={[0.71, 0.022, 0.034]}><instances.pCube328_aiStandardSurface3_0/></group>
                    <group name="pCube329" position={[11.795, 3.532, -0.001]} rotation={[-1.566, 0.058, 0]} scale={[0.71, 0.014, 0.034]}><instances.pCube329_aiStandardSurface3_0/></group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/energy_bar_v2.glb')