/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: karmadefender (https://sketchfab.com/karmadefender)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/granola-bar-9efbda4311a64782a73b5ce382a6e841
Title: Granola Bar
*/

import *d THREE from 'three'
import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    pCube3_aiStandardSurface1_0: THREE.Mesh
    // ... all your other nodes here ...
    pCube329_aiStandardSurface3_0: THREE.Mesh
  }
  materials: {
    aiStandardSurface1: THREE.MeshStandardMaterial
    aiStandardSurface2: THREE.MeshStandardMaterial
    aiStandardSurface3: THREE.MeshStandardMaterial
  }
}

// Wrap your component in forwardRef
export const Energybar = forwardRef<THREE.Group>((props, ref) => {
  const { nodes, materials } = useGLTF('/granola_bar_3d.glb') as GLTFResult
  
  // Assign the ref to the main group
  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-0.0479383, 0.0251902, 0.1388813]}>
        {/* All your <mesh> elements remain unchanged inside this group */}
        <mesh
          geometry={nodes.pCube3_aiStandardSurface1_0.geometry}
          material={materials.aiStandardSurface1}
          scale={[20.6122513, 5.8417349, 3.5186796]}
        />
        <mesh
          geometry={nodes.pCube6_aiStandardSurface2_0.geometry}
          material={materials.aiStandardSurface2}
          position={[-11.2628765, 4.1092715, -0.0006527]}
          rotation={[-1.5738335, 0.0750538, -0.0030963]}
          scale={[0.5357696, 0.0215652, 0.0344057]}
        />
        {/* ... truncated for brevity ... all other meshes go here ... */}
        <mesh
          geometry={nodes.pCube329_aiStandardSurface3_0.geometry}
          material={materials.aiStandardSurface3}
          position={[11.7951622, 3.5321004, -0.0007819]}
          rotation={[-1.5664596, 0.058433, 0.0003602]}
          scale={[0.7098053, 0.0144907, 0.034]}
        />
      </group>
    </group>
  )
})

useGLTF.preload('/granola_bar_3d.glb')